import json

from fastapi import APIRouter, File, Form, UploadFile, HTTPException, Depends
from sqlalchemy.orm import Session

from app.schemas.analysis import AnalysisResponse
from app.schemas.cv import ParsedCvResponse
from app.schemas.keywords import (
    KeywordExtractionRequest,
    KeywordExtractionResponse,
)
from app.schemas.matching import MatchRequest, MatchResponse
from app.schemas.pipeline import (
    AnalyzeCvRequest,
    AnalyzeCvResponse,
    AnalyzeJobRequest,
    AnalyzeJobResponse,
    InterviewPrepRequest,
    InterviewPrepResponse,
)
from app.services.cv_parser import parse_cv
from app.services.keyword_store import save_keyword_list, get_keyword_list_by_source_text
from app.services.keyword_clean import (
    clean_job_text,
    normalize_keywords,
    extract_whitelist_keywords,
)
from app.services.keyword_fallback import extract_keywords_fallback
from app.services.keyword_crf import extract_keywords_crf
from app.services.keyword_transformer import extract_keywords_transformer
from app.services.lang_detect import is_english_text
from app.services.llm import (
    LLMServiceError,
    analyze_job_text,
    extract_job_keywords,
    generate_interview_prep,
)
from app.core.config import settings
from app.services.matching import compute_match_score
from app.db.session import get_db
from app.api.routes.auth import get_current_user_optional
from app.services.activity_logger import record_activity
from app.services.fair_use import enforce_fair_use_or_raise

router = APIRouter()


@router.post("", response_model=AnalysisResponse)
async def analyze_cv(
    file: UploadFile = File(...),
    job_description: str = Form(...),
) -> AnalysisResponse:
    MAX_FILE_SIZE = 5 * 1024 * 1024  # 5 MB
    file_bytes = await file.read(MAX_FILE_SIZE + 1)
    if len(file_bytes) > MAX_FILE_SIZE:
        raise HTTPException(status_code=413, detail="File too large. Maximum size is 5MB.")
    parsed = parse_cv(file_bytes=file_bytes, filename=file.filename or "")
    return AnalysisResponse(
        score=0,
        missing_keywords=[],
        optimized_cv=parsed.raw_text,
        feedback="Stage 3: extracted plain text from CV PDF/TXT.",
    )


@router.post("/upload", response_model=ParsedCvResponse)
async def upload_cv(file: UploadFile = File(...)) -> ParsedCvResponse:
    MAX_FILE_SIZE = 5 * 1024 * 1024  # 5 MB
    file_bytes = await file.read(MAX_FILE_SIZE + 1)
    if len(file_bytes) > MAX_FILE_SIZE:
        raise HTTPException(status_code=413, detail="File too large. Maximum size is 5MB.")
    try:
        parsed = parse_cv(file_bytes=file_bytes, filename=file.filename or "")
    except Exception as exc:
        raise HTTPException(status_code=400, detail="Failed to parse CV file") from exc


    structured_payload = {
        "skills": parsed.skills,
        "work_experience": parsed.work_experience,
        "education": parsed.education,
        "achievements": parsed.achievements,
    }

    pretty_json = json.dumps(structured_payload, indent=2, ensure_ascii=False)
    markdown = (
        "## Skills\n"
        + ("\n".join(f"- {item}" for item in parsed.skills) or "- —")
        + "\n\n## Experience\n"
        + ("\n".join(f"- {item}" for item in parsed.work_experience) or "- —")
        + "\n\n## Education\n"
        + ("\n".join(f"- {item}" for item in parsed.education) or "- —")
        + "\n\n## Achievements\n"
        + ("\n".join(f"- {item}" for item in parsed.achievements) or "- —")
    )

    return ParsedCvResponse(
        raw_text=parsed.raw_text,
        skills=parsed.skills,
        work_experience=parsed.work_experience,
        education=parsed.education,
        achievements=parsed.achievements,
        pretty_json=pretty_json,
        markdown=markdown,
        feedback="CV text extracted.",
    )


@router.post("/cv", response_model=AnalyzeCvResponse)
def analyze_cv_text_route(
    payload: AnalyzeCvRequest,
    db: Session = Depends(get_db),
    current_user=Depends(get_current_user_optional),
) -> AnalyzeCvResponse:
    try:
        analysis = analyze_cv_text(payload.cv_text)
    except LLMServiceError as exc:
        raise HTTPException(status_code=exc.status_code, detail=str(exc)) from exc
    except Exception as exc:
        raise HTTPException(status_code=500, detail="Unexpected server error") from exc

    if current_user:
        record_activity(db, user_id=current_user.id, action="CV analysis", meta={})
    return AnalyzeCvResponse(
        cv_analysis=analysis,
        feedback="CV analysis generated by LLM.",
    )


@router.post("/job", response_model=AnalyzeJobResponse)
def analyze_job_text_route(
    payload: AnalyzeJobRequest,
    db: Session = Depends(get_db),
    current_user=Depends(get_current_user_optional),
) -> AnalyzeJobResponse:
    try:
        analysis = analyze_job_text(payload.job_text)
    except LLMServiceError as exc:
        raise HTTPException(status_code=exc.status_code, detail=str(exc)) from exc
    except Exception as exc:
        raise HTTPException(status_code=500, detail="Unexpected server error") from exc

    if current_user:
        record_activity(db, user_id=current_user.id, action="Job analysis", meta={})
    return AnalyzeJobResponse(
        job_analysis=analysis,
        feedback="Job analysis generated by LLM.",
    )


@router.post("/keywords", response_model=KeywordExtractionResponse)
def extract_keywords(
    payload: KeywordExtractionRequest,
    db: Session = Depends(get_db),
    current_user=Depends(get_current_user_optional),
) -> KeywordExtractionResponse:
    cleaned_text = clean_job_text(payload.job_text)
    use_ml = is_english_text(cleaned_text)
    try:
        if use_ml:
            result = extract_keywords_transformer(cleaned_text)
            if result and result.skills:
                feedback = "Transformer keywords generated."
            else:
                result = extract_keywords_crf(cleaned_text)
                if result and result.skills:
                    feedback = "CRF keywords generated."
                else:
                    result = extract_job_keywords(cleaned_text)
                    feedback = "LLM keywords generated."
        else:
            # Non-English text — skip ML models, go straight to LLM
            result = extract_job_keywords(cleaned_text)
            feedback = "LLM keywords generated (non-English text)."
    except LLMServiceError:
        cached = get_keyword_list_by_source_text(db, payload.job_text)
        if cached:
            result = cached
            feedback = "Cached keywords loaded."
        else:
            result = extract_keywords_fallback(cleaned_text)
            feedback = "Fallback keywords generated (LLM unavailable)."
    except Exception as exc:
        raise HTTPException(status_code=500, detail="Unexpected server error") from exc

    whitelist_hits = extract_whitelist_keywords(cleaned_text, limit=settings.max_ats_keywords)
    result.skills = normalize_keywords(whitelist_hits + result.skills)
    result.requirements = normalize_keywords(result.requirements)

    keyword_list_id = save_keyword_list(
        db=db,
        source_text=payload.job_text,
        skills=result.skills,
        requirements=result.requirements,
    )

    if current_user:
        record_activity(db, user_id=current_user.id, action="Keyword extraction", meta={})

    return KeywordExtractionResponse(
        skills=result.skills,
        requirements=result.requirements,
        keyword_list_id=keyword_list_id,
        feedback=feedback,
    )


@router.post("/match", response_model=MatchResponse)
def match_cv_job(
    payload: MatchRequest,
    db: Session = Depends(get_db),
) -> MatchResponse:
    # Note: this endpoint is intentionally unauthenticated.
    keywords: list[str] | None = None
    feedback = "Match score computed from extracted keywords."

    if payload.keywords:
        keywords = normalize_keywords(payload.keywords, limit=settings.max_ats_keywords)
        feedback = "Match score computed from provided keywords."
    else:
        try:
            cleaned_text = clean_job_text(payload.job_text)
            use_ml = is_english_text(cleaned_text)
            if use_ml:
                keyword_result = extract_keywords_transformer(cleaned_text)
                if keyword_result and keyword_result.skills:
                    keywords = normalize_keywords(
                        extract_whitelist_keywords(cleaned_text, limit=settings.max_ats_keywords)
                        + keyword_result.skills
                        + keyword_result.requirements,
                        limit=settings.max_ats_keywords,
                    )
                    feedback = "Match score computed from transformer keywords."
                else:
                    keyword_result = extract_keywords_crf(cleaned_text)
                    if keyword_result and keyword_result.skills:
                        keywords = normalize_keywords(
                            extract_whitelist_keywords(cleaned_text, limit=settings.max_ats_keywords)
                            + keyword_result.skills
                            + keyword_result.requirements,
                            limit=settings.max_ats_keywords,
                        )
                        feedback = "Match score computed from CRF keywords."
                    else:
                        keyword_result = extract_job_keywords(cleaned_text)
                        keywords = normalize_keywords(
                            extract_whitelist_keywords(cleaned_text, limit=settings.max_ats_keywords)
                            + keyword_result.skills
                            + keyword_result.requirements,
                            limit=settings.max_ats_keywords,
                        )
                        feedback = "Match score computed from LLM keywords."
            else:
                # Non-English — use LLM directly
                keyword_result = extract_job_keywords(cleaned_text)
                keywords = normalize_keywords(
                    keyword_result.skills + keyword_result.requirements,
                    limit=settings.max_ats_keywords,
                )
                feedback = "Match score computed from LLM keywords (non-English text)."
        except LLMServiceError:
            cached = get_keyword_list_by_source_text(db, payload.job_text)
            if cached:
                keywords = normalize_keywords(
                    extract_whitelist_keywords(cleaned_text, limit=settings.max_ats_keywords)
                    + cached.skills
                    + cached.requirements,
                    limit=settings.max_ats_keywords,
                )
                feedback = "Match score computed from cached keywords."
                keyword_result = cached
            else:
                keyword_result = extract_keywords_fallback(cleaned_text)
                keywords = normalize_keywords(
                    extract_whitelist_keywords(cleaned_text, limit=settings.max_ats_keywords)
                    + keyword_result.skills
                    + keyword_result.requirements,
                    limit=settings.max_ats_keywords,
                )
                feedback = "Match score computed from fallback keywords."
        except Exception as exc:
            raise HTTPException(
                status_code=500, detail="Unexpected server error"
            ) from exc

        save_keyword_list(
            db=db,
            source_text=payload.job_text,
            skills=keyword_result.skills,
            requirements=keyword_result.requirements,
        )

    match_percent, matched, missing = compute_match_score(payload.cv_text, keywords or [])

    return MatchResponse(
        match_percent=match_percent,
        matched_keywords=matched,
        missing_keywords=missing,
        total_keywords=len(matched) + len(missing),
        feedback=feedback,
    )


@router.post("/interview-prep", response_model=InterviewPrepResponse)
def interview_prep_route(
    payload: InterviewPrepRequest,
    db: Session = Depends(get_db),
    current_user=Depends(get_current_user_optional),
) -> InterviewPrepResponse:
    if not current_user:
        raise HTTPException(status_code=401, detail="Authentication required.")

    enforce_fair_use_or_raise(db, current_user)
    if not current_user.can_use("prep"):
        raise HTTPException(status_code=402, detail="Daily Interview Prep limit reached. Please upgrade your plan.")

    try:
        questions = generate_interview_prep(
            job_text=payload.job_text,
            missing_keywords=payload.missing_keywords,
            ui_language=payload.ui_language,
        )
    except LLMServiceError as exc:
        raise HTTPException(status_code=exc.status_code, detail=str(exc)) from exc
    except Exception as exc:
        raise HTTPException(status_code=500, detail="Unexpected server error") from exc

    if current_user:
        if payload.analysis_id:
            from app.models.analysis import Analysis
            from sqlalchemy.orm.attributes import flag_modified
            analysis = db.query(Analysis).filter(
                Analysis.id == payload.analysis_id,
                Analysis.user_id == current_user.id
            ).first()
            if analysis:
                new_result = dict(analysis.result_json or {})
                new_result["interview_questions"] = questions
                analysis.result_json = new_result
                flag_modified(analysis, "result_json")
                db.add(analysis)
                db.commit()
                
        if current_user.subscription_tier == "single":
            current_user.daily_prep_count = max(0, current_user.daily_prep_count - 1)
        else:
            current_user.daily_prep_count += 1
        db.add(current_user)
        db.commit()
        record_activity(db, user_id=current_user.id, action="Interview prep", meta={"analysis_id": payload.analysis_id})

    return InterviewPrepResponse(
        questions=questions, feedback="Interview questions generated by LLM."
    )
