import type { Language } from "./translations";
import type { BlogPost } from "./blogPosts";

type Dict = Array<[string, string]>;

const DICTS: Record<Exclude<Language, "en">, Dict> = {
  uk: [
    ["How to ", "Як "],
    ["Top ", "Топ "],
    ["Use ", "Використовуйте "],
    ["Resume", "Резюме"],
    ["resume", "резюме"],
    ["CV", "CV"],
    ["ATS", "ATS"],
    ["score", "бал"],
    ["Score", "Бал"],
    ["job description", "опис вакансії"],
    ["keywords", "ключові слова"],
    ["Keyword", "Ключове слово"],
    ["checklist", "чекліст"],
    ["guide", "гайд"],
    ["tips", "поради"],
    ["workflow", "процес"],
    ["optimization", "оптимізація"],
    ["optimize", "оптимізувати"],
    ["published", "опубліковано"],
    ["Key takeaway", "Ключова думка"],
    ["Tip", "Порада"],
    ["career switch", "зміна кар'єри"],
    ["impact", "вплив"],
    ["interview", "співбесіда"],
    ["cover letter", "супровідний лист"],
    ["remote", "віддалена робота"],
    ["weekly", "щотижневий"],
    ["application", "заявка"],
    ["history", "історія"],
    ["before", "до"],
    ["after", "після"],
    [" and ", " та "],
    [" with ", " з "],
    [" for ", " для "],
    [" to ", " щоб "],
  ],
  pl: [
    ["How to ", "Jak "],
    ["Top ", "Najważniejsze "],
    ["Use ", "Użyj "],
    ["Resume", "CV"],
    ["resume", "cv"],
    ["CV", "CV"],
    ["ATS", "ATS"],
    ["score", "wynik"],
    ["Score", "Wynik"],
    ["job description", "opis stanowiska"],
    ["keywords", "słowa kluczowe"],
    ["checklist", "checklista"],
    ["guide", "poradnik"],
    ["tips", "wskazówki"],
    ["workflow", "proces"],
    ["optimization", "optymalizacja"],
    ["optimize", "optymalizować"],
    ["published", "opublikowano"],
    ["Key takeaway", "Najważniejszy wniosek"],
    ["Tip", "Wskazówka"],
    ["career switch", "zmiana kariery"],
    ["impact", "wpływ"],
    ["interview", "rozmowa rekrutacyjna"],
    ["cover letter", "list motywacyjny"],
    ["remote", "zdalna"],
    ["weekly", "tygodniowy"],
    ["application", "aplikacja"],
    ["history", "historia"],
    ["before", "przed"],
    ["after", "po"],
    [" and ", " i "],
    [" with ", " z "],
    [" for ", " dla "],
    [" to ", " aby "],
  ],
  sk: [
    ["How to ", "Ako "],
    ["Top ", "Top "],
    ["Use ", "Použite "],
    ["Resume", "Životopis"],
    ["resume", "životopis"],
    ["CV", "CV"],
    ["ATS", "ATS"],
    ["score", "skóre"],
    ["Score", "Skóre"],
    ["job description", "popis práce"],
    ["keywords", "kľúčové slová"],
    ["checklist", "kontrolný zoznam"],
    ["guide", "sprievodca"],
    ["tips", "tipy"],
    ["workflow", "postup"],
    ["optimization", "optimalizácia"],
    ["optimize", "optimalizovať"],
    ["published", "publikované"],
    ["Key takeaway", "Hlavná myšlienka"],
    ["Tip", "Tip"],
    ["career switch", "zmena kariéry"],
    ["impact", "dopad"],
    ["interview", "pohovor"],
    ["cover letter", "motivačný list"],
    ["remote", "remote"],
    ["weekly", "týždenný"],
    ["application", "žiadosť"],
    ["history", "história"],
    ["before", "pred"],
    ["after", "po"],
    [" and ", " a "],
    [" with ", " s "],
    [" for ", " pre "],
    [" to ", " na "],
  ],
  cs: [
    ["How to ", "Jak "],
    ["Top ", "Top "],
    ["Use ", "Použijte "],
    ["Resume", "Životopis"],
    ["resume", "životopis"],
    ["CV", "CV"],
    ["ATS", "ATS"],
    ["score", "skóre"],
    ["Score", "Skóre"],
    ["job description", "popis pozice"],
    ["keywords", "klíčová slova"],
    ["checklist", "checklist"],
    ["guide", "průvodce"],
    ["tips", "tipy"],
    ["workflow", "postup"],
    ["optimization", "optimalizace"],
    ["optimize", "optimalizovat"],
    ["published", "publikováno"],
    ["Key takeaway", "Hlavní myšlenka"],
    ["Tip", "Tip"],
    ["career switch", "změna kariéry"],
    ["impact", "dopad"],
    ["interview", "pohovor"],
    ["cover letter", "motivační dopis"],
    ["remote", "na dálku"],
    ["weekly", "týdenní"],
    ["application", "žádost"],
    ["history", "historie"],
    ["before", "před"],
    ["after", "po"],
    [" and ", " a "],
    [" with ", " s "],
    [" for ", " pro "],
    [" to ", " pro "],
  ],
  es: [
    ["How to ", "Cómo "],
    ["Top ", "Principales "],
    ["Use ", "Usa "],
    ["Resume", "Currículum"],
    ["resume", "currículum"],
    ["CV", "CV"],
    ["ATS", "ATS"],
    ["score", "puntuación"],
    ["Score", "Puntuación"],
    ["job description", "descripción del puesto"],
    ["keywords", "palabras clave"],
    ["checklist", "checklist"],
    ["guide", "guía"],
    ["tips", "consejos"],
    ["workflow", "flujo de trabajo"],
    ["optimization", "optimización"],
    ["optimize", "optimizar"],
    ["published", "publicado"],
    ["Key takeaway", "Idea clave"],
    ["Tip", "Consejo"],
    ["career switch", "cambio de carrera"],
    ["impact", "impacto"],
    ["interview", "entrevista"],
    ["cover letter", "carta de presentación"],
    ["remote", "remoto"],
    ["weekly", "semanal"],
    ["application", "solicitud"],
    ["history", "historial"],
    ["before", "antes"],
    ["after", "después"],
    [" and ", " y "],
    [" with ", " con "],
    [" for ", " para "],
    [" to ", " para "],
  ],
};

function localizeText(text: string, lang: Language): string {
  if (lang === "en") {
    return text;
  }

  const dict = DICTS[lang];
  let next = text;
  for (const [from, to] of dict) {
    next = next.split(from).join(to);
  }
  return next;
}

export function localizeBlogPost(post: BlogPost, lang: Language): BlogPost {
  if (lang === "en") {
    return post;
  }

  return {
    ...post,
    title: localizeText(post.title, lang),
    excerpt: localizeText(post.excerpt, lang),
    lead: localizeText(post.lead, lang),
    sections: post.sections.map((section) => ({
      title: localizeText(section.title, lang),
      body: localizeText(section.body, lang),
    })),
    takeawayTitle: localizeText(post.takeawayTitle, lang),
    takeawayBody: localizeText(post.takeawayBody, lang),
  };
}
